# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        carousel:
            quality: 100
            filters:
                thumbnail:
                    size: [ 1920, 1088 ]
                    mode: outbound
                    allow_upscale: true

        card:
            quality: 100
            filters:
                thumbnail:
                    size: [ 800, 600 ]
                    mode: outbound
                    allow_upscale: true

        cards:
            quality: 100
            filters:
                thumbnail:
                    size: [ 480, 620 ]
                    mode: outbound
                    allow_upscale: true

        img_sub:
            quality: 100
            filters:
                thumbnail:
                    size: [ 1600, 1000 ]
                    mode: outbound
                    allow_upscale: true

        img_head:
            quality: 100
            filters:
                thumbnail:
                    size: [ 1200, 300 ]
                    mode: outbound
                    allow_upscale: true

        card_blg:
            quality: 100
            filters:
                thumbnail:
                    size: [ 400, 225 ]
                    mode: outbound
                    allow_upscale: true

        mgm:
            quality: 100
            filters:
                thumbnail:
                    size: [ 500, 500 ]
                    mode: outbound
                    allow_upscale: true



